### ISSUE TITLE
Tracking Resumption

### ISSUE THREAD

**Issue by inertia186** [MattyIce/bottracker#12]
There was a bid bot that went down for two days and got dropped from steembottracker.com.  The tracker showed it down for a while then it got delisted.

The bot has resumed voting and the bot operator did an `account_update` broadcast, but it didn't get relisted on steembottracker.com.  Is there some other way to get it relisted?

Bot in question: `@booster`

**Comment by MattyIce** [comment]
Booster was re-added (a while ago, just seeing this issue now), thanks for reporting!
