### ISSUE TITLE
curation calculator slider is not working when the value is over 500$

### ISSUE THREAD

**Issue by TheGoldenPhoenix** [MattyIce/bottracker#18]
#### Actual behavior
When using @yabapmatt [curation calculator](https://steembottracker.com/curation_calculator.html?#result) with posts that have a value more than 500$ the slider will not work as expected and the max value is fixed to 500$ .
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517261901/yta6thyhxyppclujk89y.png)
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517261431/r2zamvutqpynhfhvhnyz.png)

#### Expected behavior
The slider max should be a variable that depend on the initial value of the post.
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517262329/vgn97yzsrjumbrpgcgvj.png)

#### How to reproduce
1- Go to https://steembottracker.com/curation_calculator.html?
2- Enter the requested information  and use a post with a value > 500$ you can use this one : https://steemit.com/steemstem/@steemstem/promoting-steemit-going-down-inside-the-large-hadron-collider-at-cern-with-steemstem
3- Now Try to move the slider  and check the min/max value of the slider.
* Browser: 
Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
* Operating system:
Windows 10

<hr>
<h1> <blockquote>𝕨𝕖 𝕘𝕠 𝕤𝕝𝕠𝕨 𝕓𝕦𝕥 𝕨𝕖 𝕘𝕠 𝕗𝕦𝕣𝕥𝕙𝕖𝕣 @thegoldenphoenix</blockquote>
<hr>
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thegoldenphoenix/curation-calculator-slider-is-not-working-when-the-value-is-over-500usd">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by MattyIce** [comment]
This should be fixed now, thanks for reporting the issue!

**Comment by TheGoldenPhoenix** [comment]
you are welcome @MattyIce  ;)
