### ISSUE TITLE
Steem Bot Tracker 404 Error

### ISSUE THREAD

**Issue by tobias-g1** [MattyIce/bottracker#19]
#### Expected behavior
Clicking on the logo shown in the left of the top navigation bar should take you to the home page of the site.

#### Actual behavior
Clicking on the logo shown in the left of the top navigation bar should takes you to a page that shows a 404 when clicked on certain pages. 

#### How to reproduce
A) Visit https://steembottracker.com/ 
B) Click on Tools in the top navigation
C) Click on Curation Estimator
D) Once the page has loaded on the curation estimator page, click on the steemtracker logo located at the top left corner of page in the navigation area.

Browser: Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit))
Operating system: MacOS HighSierra Version 10.13

#### Recording Of The Bug
A video of the bug can be found here: https://d.tube/#!/v/tobias-g/u9ktmw23
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/steem-bot-tracker-404-error">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by MattyIce** [comment]
This should be fixed now, thanks for reporting the issue!
