### ISSUE TITLE
Steem Connect Fails from Curation Reward Estimator

### ISSUE THREAD

**Issue by tobias-g1** [MattyIce/bottracker#20]
#### Expected behavior
You should be able to login via Steem Connect on any page on the site. 

#### Actual behavior
When you try to login on the curation rewards estimator page steem connect returns a failure message. 

#### How to reproduce
A) Visit https://steembottracker.com/
B) Click on Tools in the top navigation
C) Click on Curation Estimator
D) Once the page has loaded on the curation estimator page, click on login located at the top right of the page. 
E) It will take you to a page which shows an error when you try to login. 

Browser: Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit))
Operating system: MacOS HighSierra Version 10.13

#### Recording Of The Bug
A recording of the bug can be found here: https://d.tube/#!/v/tobias-g/tqjmvkpy
 
Note: I found this post following my previous contribution and is the same bug as the current bug has been resolved and this issue is still apparent at the time of writing. 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/steem-connect-fails-from-curation-reward-estimator">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by MattyIce** [comment]
This should be fixed now, thanks for reporting the issue!
