### ISSUE TITLE
Tracking Resumption (again)

### ISSUE THREAD

**Issue by LKNX** [MattyIce/bottracker#27]
There was a bid bot that went down for four days and got dropped from steembottracker.com. The tracker showed it down for a while then it got delisted.

The bot has resumed voting and the bot operator did an account_update broadcast, but it didn't get relisted on steembottracker.com. Is there some other way to get it relisted?

Bot in question: @booster

**Comment by MattyIce** [comment]
I need to manually relist a bot after it is taken off the site. @booster is back on now.
