### ISSUE TITLE
Security Issue, option to not use iframe for steemconnect?

### ISSUE THREAD

**Issue by kirkins** [MattyIce/bottracker#31]
Hi, I'm enjoying this application but the Steem Connect pop-up says verify that you are on the correct URL.

This can be done by right clicking on the iframe and selecting open as a new tab, or view frame source.

For those who want to verify the correct URL each time it's exhausting. It would be great if there was an option to use new tab instead of an iframe.

_Edit: This would also make the site work with Brave https://github.com/brave/browser-laptop/issues/13392_

**Comment by MattyIce** [comment]
Thanks @kirkins, you're absolutely correct. I updated the site to load the steem connect page in a pop-up window so that the URL can be easily validated.
