### ISSUE TITLE
Bottracker web page copy

### ISSUE THREAD

**Issue by order4adwriter** [MattyIce/bottracker#32]
Hello@Mattyice,

I am a professional copywriter looking for open source  projects here on git hub to contribute to.

I can see from the bottracker website that it needs certain web pages  such as an An About Us page, FAQ page, Privacy Policy/ Terms Of Use Page, and so on

I can help you write the webpage copy/content  for each of these pages if you'd like... so you could paste them in the respective pages when they are created.

The question though is... can I  write them ...and if yes, will they be merged into your master repo here on github?

Either way, please let me know asap so I could get started immediately.... or not.

 I can be reached on Discord via @order4adwriter if you'd like us to have a chat about it.

Thanks.

**Comment by MattyIce** [comment]
Thank you but I am not interested at this time.
