### ISSUE TITLE
[Bug Hunting] Steembottracker application - Bid History

### ISSUE THREAD

**Issue by esaksham** [MattyIce/bottracker#33]
#### Expected behavior

The Steembottracker is a bidding application build by @yabapmatt that provides a dynamic window for a user to buy votes from the bidding bots, displaying their Minimum Value, Suggested Bid and ROI like parameters. So that a user can bid on the voting power of a particular bot.

*It's expected that when a user clicks on the User --> Bid History It should display the History of Bids made by the logged in user.*

#### Actual behavior

Currently, the Bid History is not getting displayed at all irrespective of the waiting time.

#### How to reproduce

1. Open the https://steembottracker.com/ on Web Browser (Google Chrome is used here).
2. Login with a steemit user using steemconnect.
2. Navigate to User--> Bid History
3. Frame opens up but no data is displayed.

* Browser:  Google Chrome/ Mozilla Firefox
* Operating system: Windows 8.1

#### Recording Of The Bug

 ![SteembotTrackerBidHistory.gif](https://cdn.utopian.io/posts/8af158179619b367f2611f20c36e27d097b1SteembotTrackerBidHistory.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@saksham/bug-hunting-steembottracker-application-bid-history">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by MattyIce** [comment]
This has been fixed.
