### ISSUE TITLE
Permission to contribute valuable content to your project (FAQ, About Us, Contact Us, Privacy Policy)

### ISSUE THREAD

**Issue by RolletOso** [MattyIce/bottracker#36]
Hello,

The idea of your project is amazing and while you are doing an awesome job with technical aspects and coding, i will like to take some weight off you by offering copywriting services.

I will contribute a privacy policy which is a statement or a legal document that discloses some or all of the ways a party gathers, uses, discloses, and manages a customer or client's data.

I will contribute a compelling About Us content that will tell off your founding story, a content that will show off your the core or your project, and will answer the most pressing question new and old users may have about your project.

I will also create FAQ Content. I will use Frequently asked questions or Questions and Answers to list out questions and answers, all supposed to be commonly asked in some context, and pertaining to your project and more insight to the project.

I am willing to contribute to the copywriting aspect of your project so you can put more effort on the technicalities and perform at your optimum best.

Anticipating Your response.

Thank you.

**Comment by MattyIce** [comment]
Thank you but I am not interested in this at this time.
