### ISSUE TITLE
24 hour Analysis and cross reference of profits made on steembottracker

### ISSUE THREAD

**Issue by yalzeee** [MattyIce/bottracker#39]
I will be doing an analysis for each pay out made from each bot on the steembottracker site to estimate most profitable bots for bidding, and factors that affect interest or profitability. Any charts of analysis available would be greatly appreciated

**Comment by MattyIce** [comment]
@yalzeee I have not done any analysis like this and I don't have any charts for you. This doesn't really qualify as an issue on the bot tracker project.
