### ISSUE TITLE
bot listing in bottracker. @upyourpost

### ISSUE THREAD

**Issue by jjerryhan** [MattyIce/bottracker#40]
Hello @MattyIce,

I started new upvote bot. http://steemit.com/@upyourpost.
And I setup the json_metadata on my upvoting bot @upyourpost.
Why my new bot was not listed on the steembottracker ? 
II want to know about how to register my bot to the steembottracker.

**Comment by jjerryhan** [comment]
I really want to get listed in bottracker site with my new biding bot http://steemit.com/@upyourpost.
What is the exact barrier for?

I saw the many bots are providing their current api from the same host : https://postpromoter.com/api
Anyone can notice it from here : https://steembottracker.net/bid_bots
Please see the 'api_url' information for each bot on it.

I want to know about what is the relation between bottracker and some bots which are currently providing api from same host. 

Are you providing some wrapper module to the bot operator for providing api from the https://postpromoter.com host?
How these bots are providing their own api from the same https://postpromoter.com host?

I really want to know what is the needed qualification for listing up in bottracker site?

**Comment by MattyIce** [comment]
@jjerryhan sorry for the slow reply - in the future please contact me on Discord and i will see it more quickly. @upyourpost has been added to the site now. 

Regarding bots using postpromoter domain names, those are bots I run / host for other people.

**Comment by jjerryhan** [comment]
@MattyIce Thanks for your cooperation. I will contact you via Discord after now. Now I understand for the bots using postpromoter domain.  Thanks again.
