### ISSUE TITLE
Stop using CoinMarket Cap Average STEEM/SBD Price

### ISSUE THREAD

**Issue by officiallymarky** [MattyIce/bottracker#41]
I'm copypasting the same [issue I made on Post Promoter script](https://github.com/MattyIce/postpromoter/issues/85) here as it is also relevant to Steembottracker.com.

CoinMarketCap average price is artificially inflated due to HitBTC's price insanity that happens from time to time.  You haven't been able to Deposit/Withdraw STEEM/SBD from Hitbtc for a long time yet it frequently pumps to extremely high levels.  Currently over $20 for SBD.

![](https://i.imgur.com/55GaJzI.png)

We also know poloniex suffers from similar issues just not as pronounced.  I recommend using an average of Bittrex & Binance to report current STEEM/SBD prices.  They will be far more realistic and consistent.

Currently Steembottracker and Post Promoter script are reporting $3.45 SBD price, but it is no where near that in reality.

![](https://i.imgur.com/pM7pkvG.png)

**Comment by rychardemanne** [comment]
Agree.

Another option is to use a median price - that will ignore outliers at both ends.

I think this is quite urgent for bidbot users.

**Comment by MattyIce** [comment]
Switched to Bittrex for now for SBD price.
