### ISSUE TITLE
Site Performance Recently

### ISSUE THREAD

**Issue by officiallymarky** [MattyIce/bottracker#43]
Somewhere in the last few months, the site has become very slow.  Most notably hitting the dropdown for a bot to select details.  It takes quite a few tries sometimes and is very slow.  The site also feels very sluggish in general compared to where it was a few months ago. 

It feels inconsistent, sometimes it isn't so bad, other times it feels it really struggling.  I typically have most bots filtered out as I keep the filter at 50 minimum.

**Comment by MattyIce** [comment]
@themarkymark-steem is this still happening? I've been checking since you've submitted this issue and I haven't noticed it be slow at all.

**Comment by officiallymarky** [comment]
Yes, clicking "Actions" is painfully slow a lot of the times and requires many clicks, sending video.

**Comment by officiallymarky** [comment]
Problem solved by disabling uBlock Origin on the site, it appears to be what is slowing it down for me.  Telling it to ignore steembottracker.com gives me near-instant responsiveness now.
